# Generated by Django 4.2.7 on 2023-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritedEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=60)),
                ('venue', models.CharField(max_length=60)),
                ('thumbnailURL', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=60)),
            ],
        ),
    ]
