# Generated by Django 4.2.7 on 2023-11-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0002_favoritedevents_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.CharField(max_length=60)),
                ('venue', models.CharField(max_length=60)),
                ('thumbnailURL', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='FavoritedEvents',
        ),
    ]
