# Generated by Django 4.2.7 on 2023-12-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0004_rename_address_favoriteevents_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteevents',
            name='eventId',
            field=models.CharField(default='x', max_length=60),
        ),
    ]
