# Generated by Django 4.2.7 on 2023-12-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0005_favoriteevents_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteevents',
            name='eventId',
            field=models.CharField(max_length=60),
        ),
    ]
