# Generated by Django 4.2.8 on 2023-12-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0007_rename_eventid_favoriteevents_entry_model_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteevents',
            name='is_going',
            field=models.BooleanField(default=False),
        ),
    ]
