# Generated by Django 4.2.7 on 2023-12-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0009_remove_favoriteevents_event_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteevents',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
    ]
