# Generated by Django 4.2.7 on 2023-12-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0010_favoriteevents_is_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteevents',
            name='time',
            field=models.CharField(default='10', max_length=60),
            preserve_default=False,
        ),
    ]
